name: Run Locust Tests on Commit
on:
  push:
    branches:
      - main
jobs:
  locust-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install locust
    - name: Start Flask server
      run: |
        nohup python server.py &
        echo "Waiting for Flask server to start"
        sleep 30
    - name: Run Locust tests
      run: |
        locust -f locustfile.py --headless --users 10000 --spawn-rate 100 --host=http://127.0.0.1:5000 --run-time 2m
    # - name: Stop Flask server
    #   run: |
    #     kill $(lsof -t -i:5000)
